### ISSUE TITLE
Infura IPFS URL has changed, and needs to be updated in the package viewer

### ISSUE THREAD

**Issue by JHGrove3** [dappnode/explorer#36]
Infura has changed the URL of their IPFS information.  

The Dappnode Explorer pages now show an error message, instead of IPFS information.

I have made a pull request to update this URL.

Please verify, then merge the pull request.

![Infura URL Change](https://user-images.githubusercontent.com/2583972/188499230-67ac6384-b06d-47e9-8fc1-b268fe3eb630.jpg)

**Comment by dsimog01** [comment]
Closed by https://github.com/dappnode/explorer/pull/37
